apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: valuable-kingfisher-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/valuable-kingfisher-dotnet-basic